network:
  name: bit
  model: BiT-M-R50x1
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: True          # set 'True' to load pretrained model
  checkpoint: ./bit_pretrained_models/BiT-M-R50x1.npz           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
  num_block_open: -1
  normal_load: True
dataset:
  image_size: 480
ood_dataset:
  image_size: 480
