ood_dataset:
  name: cifar10_ood
  num_classes: 10

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 128
  shuffle: False
  subset: -1.0

  split_names: [val, nearood, farood]
  val:
    data_dir: /h/nng/projects/OpenOOD/data/images_classic/
    imglist_pth: /h/nng/projects/OpenOOD/data/benchmark_imglist/cifar10/val_tin.txt
  nearood:
    data_dir: /h/nng/projects/OpenOOD/data/images_classic/CIFAR-10-C
    label_pth: labels.npy
    np: True
    datasets: [brightness, contrast, defocus_blur, elastic_transform, fog, frost, gaussian_blur, gaussian_noise]
  farood:
    data_dir: /h/nng/projects/OpenOOD/data/images_classic/CIFAR-10-C
    label_pth: labels.npy
    np: True
    datasets: [glass_blur, impulse_noise, jpeg_compression, motion_blur, pixelate, saturate, shot_noise, snow, spatter, speckle_noise, zoom_blur]
