postprocessor:
  name: analog
  APS_mode: False
  skip_id: False
  postprocessor_args:
    damping: 0.0
    eigen_iter: -1
    moments_iter: -1
    eigen_epochs: 1
    moment_epochs: 1
    loss_name: ce
    temp: 1
    state_name: analog
    topk: -1
    reduce: False
    sua: False
    fuse: False
    loss_scale : 1
    root_dir: /h/nng/projects/OpenOOD/results/ekfac


