postprocessor:
  name: nak
  APS_mode: False
  skip_id: False
  postprocessor_args:
    damping: 0.0
    all_classes: True
    eigen_iter: -1
    moments_iter: -1
    state_path: None
    left_output: loss
    jac_chunk_size: 8
    moments_chunk_size: -1
    ndata_iters: 1
    right_output: loss
    sum_labels: False
    topk: -1
    mdl_weight: 0
    top_layer: False
    loss_temp: 1.0
    sample_temp: 1.0
    fsample_temp: 1.0
    floss_temp: 1.0
    empirical : False
    layer_eps: False
    sample: -1
    topp: 1.0
    relative: False
    eps_type: mean
    normalize: False
    total_eps: False
