postprocessor:
  name: nak
  APS_mode: False
  skip_id: False
  postprocessor_args:
    damping: 0.0
    all_classes: True
    eigen_iter: -1
    moments_iter: -1
    state_path: None
    left_output: loss
    jac_chunk_size: 8
    remove_top: False
    center: False
    moments_chunk_size: -1
    odin: False
    noise: 0.0014
    ndata_iters: 1
    right_output: loss
    sum_labels: False
    topk: -1
    per_class_m1: False
    sua: True
    double: False
    fuse: False
    mdl_weight: 0
    nfeature_reduce: 2000
    top_layer: False
    loss_temp: 1.0
    sample_temp: 1.0
    inverse: True
    fsample_temp: 1.0
    featskip: 1
    eigenscale: 1.0
    floss_temp: 1.0
    temp: -1.0
    layerscale: 1.0
    floss_fn: ce
    ce_weight: 1.0
    empirical : False
    ind_sample: False
    off_diag: False
    layer_eps: False
    ntrain: -1
    sample: -1
    topp: 1.0
    relative: False
    eps_type: mean
    normalize: False
    total_eps: False
