postprocessor:
  name: nak
  APS_mode: False
  use_train: False
  skip_id: False
  skip_ood: False
  fgsm: False
  epsilon: 0.0

  postprocessor_args:
    acnml: False
    nsteps: 1
    regret: linear
    natural: True
    damping: 0.0
    all_classes: True
    eigen_iter: -1
    moments_iter: -1
    state_path: None
    left_output: loss
    jac_chunk_size: 8
    remove_top: False
    reset_m1: False
    center: False
    moments_chunk_size: 64
    odin: False
    noise: 0.0014
    odin_temp: 1000
    ndata_iters: 1
    right_output: loss
    sum_labels: False
    topk: -1
    per_class_m1: False
    sua: True
    double: False
    fuse: False
    mdl_weight: 0
    nfeature_reduce: 100
    top_layer: False
    sud: True
    inverse: True
    featskip: 1
    eigenscale: 1.0
    temp: 1.0
    class_chunk_size: -1
    eigen_temp: -1.0
    remove_top_layers: 0
    remove_bot_layers: 0
    full_fim: False
    random_label: False
    sandwich: False
    moments_temp: -1.0
    grad_temp: -1.0
    whiten: False
    layerscale: 1.0
    floss_fn: ce
    ce_weight: 1.0
    empirical : False
    argmax: False
    loss_scale: 1.0
    ind_sample: False
    off_diag: False
    layer_eps: False
    ntrain: -1
    sample: -1
    topp: 1.0
    relative: False
    eps_type: mean
    normalize: False
    total_eps: False
    fisher_temp: 1.0
    only_logit: True
    swag_path: default
    nsamples: 1
    fgsm: False
    epsilon: 0.0
    fisher_regret: logit
    ce_left: False
    scale_logit: False
    variance: 0.01
    phase: False
