postprocessor:
  name: nak
  APS_mode: False
  skip_id: False
  postprocessor_args:
    damping: 0.1
    maxiter: 10
    left_output: loss
    strat: min
    right_output: loss
    topk: 10
    mdl_weight: 0
    top_layer: False
    temperature: 1.0
    layer_eps: False
