dataset:
  name: cifar100
  num_classes: 100
  image_size: 32
  pre_size: 32
  comp_index: -1
  ood_comp: cifar10
  comp_label: 0
  corruption_path: default
  prune_path: default
  prune: 0.0

  interpolation: bilinear
  normalization_type: cifar100

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  subset: -1.0

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: /h/nng/projects/OpenOOD/data/images_classic/
    imglist_pth: /h/nng/projects/OpenOOD/data/benchmark_imglist/cifar100/train_cifar100.txt
    batch_size: 128
    shuffle: True
    class_loader: True
  val:
    dataset_class: ImglistDataset
    data_dir: /h/nng/projects/OpenOOD/data/images_classic/
    imglist_pth: /h/nng/projects/OpenOOD/data/benchmark_imglist/cifar100/val_cifar100.txt
    batch_size: 200
    shuffle: False
    class_loader: False
  test:
    dataset_class: ImglistDataset
    data_dir: /h/nng/projects/OpenOOD/data/images_classic/
    imglist_pth: /h/nng/projects/OpenOOD/data/benchmark_imglist/cifar100/test_cifar100.txt
    batch_size: 200
    shuffle: False
